export type Company = {
  id: string;
  company_code: string | null;
  company_name: string;
  logo_url: string | null;
  primary_color: string | null;
  secondary_color: string | null;
  country: string | null;
  city: string | null;
  currency: string | null;
  language: string | null;
  timezone: string | null;
  phone: string | null;
  email: string | null;
  website: string | null;
  address: string | null;
  cr_number: string | null;
  vat_number: string | null;
  subscription_plan: string | null;
  subscription_status: string | null;
};